# Generated by Django 3.2.3 on 2021-06-18 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_book_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Book',
        ),
    ]
