# Generated by Django 3.2.3 on 2021-06-18 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='add',
            new_name='Add',
        ),
    ]
